name: docker-experiments

services:
  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  elasticsearch:
