name: docker-experiments

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0-arm64
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
